### PR TITLE
Admin panel

### PR DESCRIPTION
**Pull request by liamlenihan**
Ready for a pull request

### CODE REVIEW

**Comment by liamlenihan** [comment]
Results from the testing have indicated that the admin panel is working with design and functionally and is responsive in all different browsers; additionally, the CRUD operations which consist of create RSS feeds, update RSS Feeds, Delete RSS Feeds and delete RSS feeds for administrative users and I have tested this admin panel throughly to ensure it is suitable and functional for our group project. Please note amendments are likely with the admin panel and as such will require future iterations to ensure accessibility and usability.

**Comment by amigafan2003** [comment]
Hi Liam - some of this code doesn't make any sense.  Line 74 in admin_feeds.php is selecting form a table called customers and getting name, email and mobile.  Why is it doing this when this branch was to add admin rss feed functionality?

Also, there is no check to see if a user is an admin or not.  Only if they are logged in as an admin should they be able to see the admin menu item or the admin_feeds.php page.  I suggest you add a u_level column to the USERS table on the database and do a if ($_SESSION["u_level"] == "admin") check against the admin menu item.  Do the same for admin_feeds.php i.e. show a "you are not logged in as admin" instead of the table if user is not logged in as admin.

Also, line 72 wont work - we can't do "require 'database.php';".  You need to use dbconnect_inc.php or else this code will fail when uploading to the t-e-n.online server.

I recommend the following code instead:-

capture

**Comment by liamlenihan** [comment]
So, I don't know were to go from here. I dont know whether to scrap the whole code and start afresh or continue making mistakes. I am at a loss what to do?

**Comment by amigafan2003** [comment]
Code amendments:-

1:  Pulled all create, update and delete processing into mng_content.php.  Only create and update have their own pages now.
2:  Added "active" field for RSS feed - can now mark RSS feeds as active or not active.  This is required as invalid feed urls will halt the app.  Amended code in mng_feeds.php and mng_mysubscriptions.php to only show feeds that are marked as active.
3:  Added security checking so that if user is not logged in and not admin, they cannot see the admin functionality (edited nav_inc.php to hide menu item as well).
4:  Removed bootstrap css entries as it was interfering  existing main.css entries.  Copied required bootstrap css code (buttons mainly) to main.css file.  
5:  Tweaked some responsive issues for the admin table.  It's still not great as tables are deprecated now and we should be using divs instead - possible area for further enhancement.

Before this change goes live the following database amendments are required:-

1:  Add u_level column to USERS table.  varchar 255, default to value "user".  Enter admin in this column to enable admin privileges.
2:  Add category column to RSS table, varchar 255.
3:  Add active column to RSS table, varchar 1, default value "0".

Testing screenshots:-

admin_feeds security 2
admin_feeds security
admin_feeds
create security 2
create security
create
delete
update security 2
update security
update

**Review by amigafan2003 — APPROVED** [review]
Recommend for merging

**Pull request merged**
